name: msrv-build
on:
  push:
    branches: ["main"]
  pull_request:
jobs:
  msrv-build:
    name: MSRV build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Fetch toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.54.0
      - name: Use MSRV Cargo.lock
        run: cp Cargo.lock.msrv Cargo.lock
      - name: Build with MSRV
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all
          toolchain: 1.54.0
      - name: Build no-std with MSRV
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path=num_enum/Cargo.toml --target thumbv6m-none-eabi --no-default-features
          toolchain: 1.54.0
